CREATE TABLE IF NOT EXISTS portfolios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    assets TEXT NOT NULL,
    portfolio_type TEXT NOT NULL
);

DELETE FROM portfolios;

ALTER TABLE portfolios AUTO_INCREMENT = 1;

-- CREATE TABLE IF NOT EXISTS posts (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     title TEXT NOT NULL,
--     content TEXT NOT NULL
-- );